# Generated by Django 3.2.9 on 2021-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge_name', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('needs_cleaning', models.BooleanField(default=False)),
                ('canned_foods_needed', models.BooleanField(default=False)),
                ('produce_needed', models.BooleanField(default=False)),
                ('fruits_needed', models.BooleanField(default=False)),
                ('maintenance_needed', models.BooleanField(default=False)),
            ],
        ),
    ]
